# Use the correct PostgreSQL version
FROM postgres:16

# Set environment variables (customize according to your needs)
ENV POSTGRES_DB=nova_films
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Copy the dump file into the container
COPY nova_films.dump /docker-entrypoint-initdb.d/


